Repository UnBArqDsw/2020.1_G3_RecipeBuk_Documentation, pull requests merged in 2020-09, with the labels that each got.

#59 [#52] Adding package diagram
  docs/04-modelagem/diagrama-pacotes.md
  docs/_sidebar.md
  docs/assets/04-modelagem/20200917-diagrama-pacotes-back.png
  docs/assets/04-modelagem/20200917-diagrama-pacotes-front.png
  docs/dinamicas/dinamica2.md
Labels: documentation

#86 Sprint Documentation
  docs/00-sprints/modelo-sprint.md
  docs/00-sprints/planning/sprint2.md
  docs/00-sprints/planning/sprint3.md
  docs/00-sprints/planning/sprint4.md
  docs/00-sprints/results/results2.md
  docs/00-sprints/results/results3.md
  docs/00-sprints/results/results4.md
  docs/00-sprints/sprints.md
Labels: documentation, sprints

#87 [#84] Database Documentation
  docs/04-modelagem/base-dados.md
  docs/_sidebar.md
  docs/assets/04-modelagem/20200923-der.png
  docs/assets/04-modelagem/20200923-logico.png
Labels: backend, documentation

#89 [#88] Modifying USER table name
  docs/04-modelagem/base-dados.md
  docs/assets/04-modelagem/20200923-der.png
  docs/assets/04-modelagem/20200923-logico.png
  docs/assets/04-modelagem/20200924-der.png
  docs/assets/04-modelagem/20200924-logico.png
Labels: bug, documentation, enhancement

#85 [#10] - Prioritized product backlog
  docs/02-requisitos/priorizacao/backlog.md
  docs/_sidebar.md
  docs/dinamicas/dinamica1.md
  docs/index.html
Labels: documentation, requisitos
